spring:
  application:
    name: msa-api-gateway
server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
#  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  routes:
    mbti-idol-api.path: /mbti/**
#zuul.routes.msa-report-api.path=/api/report/**
#zuul.routes.msa-reservation-api.path=/api/reservation/**
#zuul.routes.msa-advertising-api.path=/api/advertising/**

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000